### ISSUE TITLE
Using Layer-2 data

### ISSUE THREAD

**Issue by ed-umb** [umbrella-network/EthCC#2]
### Prize Bounty
10,000 USDC

### Challenge Description
In this challenge we want you to as much usage as possible from UMBRELLA's Layer-2 framework  We want you to build a solution -it could have layer-2 and layer-1 code on Ethereum- that makes use of our Layer-2 data.

### Submission Requirements
- Eligible projects must utilize UMBRELLA's Layer-2 framework Smart Contract on Ethereum Kovan testnet can also be used.
- The code needs to be available for revision by the UMBRELLA Judge team
- Demo videos are strongly recommended.

### Judging Criteria
Winner will be selected considering the extent of the usage of UMBRELLA's Framework.

### Winner Announcement Date
Winners will be announced on July 30th.

### Resources

Readme: [https://umbrella-network.readme.io/docs](url)

Discord channel: [https://discord.gg/Q2BE3T7t](url)

**Comment by sarahfitria12** [comment]
![Screenshot_20210716-235703](https://user-images.githubusercontent.com/84779751/126799968-26830949-0db1-4c4c-aaf7-ab36b900f8a5.jpg)
Plis help my  . My address bsc

0x852Caa8d84f96a7b6f10943eBCadD2c8413C383b

**Comment by ed-umb** [comment]
> ![Screenshot_20210716-235703](https://user-images.githubusercontent.com/84779751/126799968-26830949-0db1-4c4c-aaf7-ab36b900f8a5.jpg)
> Plis help my . My address bsc
> 
> 0x852Caa8d84f96a7b6f10943eBCadD2c8413C383b

Hello @sarahfitria12 
Could you provide more details about the issue you're facing?

Regards

**Comment by sarahfitria12** [comment]
lost a lot of assets at this time. I really need help😭😭


Pada tanggal Sab, 24 Jul 2021 04.35, ed-umb ***@***.***>
menulis:

**Comment by ed-umb** [comment]
EthCC finished.
